name: cine_data
description: A simple movie tracker app.

dependencies:
  flutter:
    sdk: flutter
  http: any
  path_provider: any
  sqflite: "^0.11.0+1"
  url_launcher: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/loading.gif
    - assets/loadingCircle.gif
    - assets/Action.png
    - assets/Adventure.png
    - assets/Animation.png
    - assets/Comedy.png
    - assets/Crime.png
    - assets/Documentary.png
    - assets/Drama.png
    - assets/Family.png
    - assets/Fantasy.png
    - assets/History.png
    - assets/Horror.png
    - assets/Music.png
    - assets/Mystery.png
    - assets/Romance.png
    - assets/Sci-Fi.png
    - assets/Thriller.png
    - assets/TV Movie.png
    - assets/War.png
    - assets/Western.png

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Light.ttf
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
